services:
  - type: worker
    name: utkarsh-telegram-bot
    runtime: python
    plan: free
    region: singapore

    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"

    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: python bot.py
